### ISSUE TITLE
browser shows "something broke"

### ISSUE THREAD

**Issue by muralikodali** [ebdrup/html2pdf.it#29] opened 2015-06-08 05:25 UTC
pdf: /home/murali/programs/gitbag/html2pdf.it/bin/phantomjs: 1: /home/murali/programs/gitbag/html2pdf.it/bin/phantomjs: Syntax error: "(" unexpected Error: Wrong code: 2
    at ChildProcess.<anonymous> (/home/murali/programs/gitbag/html2pdf.it/lib/webservices/pdf.js:99:19)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

**Comment by nareshdb** [comment] 2016-08-23 11:09
duplicate of the issue #39

**Comment by edm00se** [comment] 2016-11-20 20:37
This looks to be a duplicate of #39 as @nareshdb pointed out. This should be addressed by the latest version in the `master` branch, which switches to `phantomjs-prebuilt` from `npm`, and should always be both available as a dependency in the project's installed `node_modules` directory, and host OS requirement of installing phantom js separately is removed; all path issues should be resolved.

**Closed by edm00se** 2016-11-20 20:37 UTC
